name: 'Certgen action'
description: 'A github action that pulls danvixent/certgen'

branding:
  icon: 'activity'
  color: 'green'

inputs:
  output-folder:
    description: 'Describe the version output folder of certgen'
    required: true
    default: '.'
  certgen-version:  
    description: 'Describe the version of certgen'
    required: true
    default: '0.1.6'
  os:
    description: 'Operating system'
    required: true

runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/download-certgen.sh ${{ inputs.os }} ${{ inputs.certgen-version }} ${{ inputs.output-folder }}
      shell: bash